name: Diagnostics

on: [push]

jobs:
  TiCS:
    name: TiCS
    runs-on: ubuntu-latest
    steps:
    - name: TICS Diagnostic
      uses: tiobe/tics-github-action@32145-version_help
      with:
        projectName: 'auto'
        installTics: true
        ticsConfiguration: 'https://testlab.tiobe.com/tiobeweb/testlab/api/cfg?name=testlab'
        tmpDir: '/tmp/c-demo'
        recalc: 'CW,CS'
        githubToken: ${{secrets.GITHUB_TOKEN}}
        ticsAuthToken: ${{secrets.TICSAUTHTOKEN}}
        pullRequestApproval: false
        mode: diagnostic
